# Generated by Django 2.2.4 on 2019-08-06 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=32, verbose_name='Текст для периода доступности')),
                ('seconds', models.IntegerField(verbose_name='Период доступности в секундах')),
            ],
            options={
                'verbose_name': 'Время доступности пасты',
                'verbose_name_plural': 'Врена доступности пасты',
            },
        ),
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=65536, verbose_name='Текст пасты')),
                ('access_time', models.DateTimeField(verbose_name='Дата и время до которого доступна паста')),
                ('access_only_from_link', models.BooleanField(default=False, verbose_name='Доступно только по ссылке')),
                ('hash', models.CharField(max_length=32, verbose_name='Хэш пасты')),
                ('access_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_app.AccessPeriod', verbose_name='Период доступности пасты')),
            ],
            options={
                'verbose_name': 'Паста',
                'verbose_name_plural': 'Пасты',
            },
        ),
    ]
